MY_TOOL_IT_NETWORK_BROADCAST_ACK=0     
MY_TOOL_IT_NETWORK_STH1=1              
MY_TOOL_IT_NETWORK_STH2=2              
MY_TOOL_IT_NETWORK_STH3=3              
MY_TOOL_IT_NETWORK_STH4=4              
MY_TOOL_IT_NETWORK_STH5=5              
MY_TOOL_IT_NETWORK_STH6=6              
MY_TOOL_IT_NETWORK_STH7=7              
MY_TOOL_IT_NETWORK_STH8=8              
MY_TOOL_IT_NETWORK_STH9=9              
MY_TOOL_IT_NETWORK_STH10=10            
MY_TOOL_IT_NETWORK_STH11=11            
MY_TOOL_IT_NETWORK_STH12=12            
MY_TOOL_IT_NETWORK_STH13=13            
MY_TOOL_IT_NETWORK_STH14=14            
MY_TOOL_IT_NETWORK_SPU1=15             
MY_TOOL_IT_NETWORK_SPU2=16             
MY_TOOL_IT_NETWORK_STU1=17             
MY_TOOL_IT_NETWORK_STU2=18             
MY_TOOL_IT_NETWORK_STU3=19             
MY_TOOL_IT_NETWORK_STU4=20             
MY_TOOL_IT_NETWORK_STU5=21             
MY_TOOL_IT_NETWORK_STU6=22             
MY_TOOL_IT_NETWORK_STU7=23             
MY_TOOL_IT_NETWORK_STU8=24             
MY_TOOL_IT_NETWORK_STU9=25             
MY_TOOL_IT_NETWORK_STU10=26            
MY_TOOL_IT_NETWORK_STU11=27            
MY_TOOL_IT_NETWORK_STU12=28            
MY_TOOL_IT_NETWORK_STU13=29            
MY_TOOL_IT_NETWORK_STU14=30            
MY_TOOL_IT_NETWORK_BROADCAST_NO_ACK=31 


NetworkNumber = {
MY_TOOL_IT_NETWORK_BROADCAST_ACK : "Broadcast with ACK",   
MY_TOOL_IT_NETWORK_STH1 : "STH1",          
MY_TOOL_IT_NETWORK_STH2 : "STH2",          
MY_TOOL_IT_NETWORK_STH3 : "STH3",          
MY_TOOL_IT_NETWORK_STH4 : "STH4",          
MY_TOOL_IT_NETWORK_STH5 : "STH5",          
MY_TOOL_IT_NETWORK_STH6 : "STH6",          
MY_TOOL_IT_NETWORK_STH7 : "STH7",          
MY_TOOL_IT_NETWORK_STH8 : "STH8",          
MY_TOOL_IT_NETWORK_STH9 : "STH9",          
MY_TOOL_IT_NETWORK_STH10 : "STH10",          
MY_TOOL_IT_NETWORK_STH11 : "STH11",          
MY_TOOL_IT_NETWORK_STH12 : "STH12",          
MY_TOOL_IT_NETWORK_STH13 : "STH13",          
MY_TOOL_IT_NETWORK_STH14 : "STH14",          
MY_TOOL_IT_NETWORK_SPU1 : "SPU1",           
MY_TOOL_IT_NETWORK_SPU2 : "SPU2",           
MY_TOOL_IT_NETWORK_STU1 : "STU1",           
MY_TOOL_IT_NETWORK_STU2 : "STU2",           
MY_TOOL_IT_NETWORK_STU3 : "STU3",           
MY_TOOL_IT_NETWORK_STU4 : "STU4",           
MY_TOOL_IT_NETWORK_STU5 : "STU5",           
MY_TOOL_IT_NETWORK_STU6 : "STU6",           
MY_TOOL_IT_NETWORK_STU7 : "STU7",           
MY_TOOL_IT_NETWORK_STU8 : "STU8",           
MY_TOOL_IT_NETWORK_STU9 : "STU9",           
MY_TOOL_IT_NETWORK_STU10 : "STU10",          
MY_TOOL_IT_NETWORK_STU11 : "STU11",          
MY_TOOL_IT_NETWORK_STU12 : "STU12",          
MY_TOOL_IT_NETWORK_STU13 : "STU13",          
MY_TOOL_IT_NETWORK_STU14 : "STU14",          
MY_TOOL_IT_NETWORK_BROADCAST_NO_ACK : "Broadcast WITHOUT ACK",
    }