name: Test ICOc
description: Test ICOc on Unix platforms
runs:
  using: composite
  steps:

    - name: Test with pytest
      # - Run all tests that do not require actual hardware
      # - Ignore ICOc user interface which uses Windows event library
      run: >
        pytest
        --ignore-glob='*network.py'
        --ignore-glob='*commander.py'
        --ignore-glob='*cli.py'
        --ignore-glob='*ui.py'
      shell: bash
