# Currently only the production tests of the STH use the following config file.

Commands:
  Path:
    # The keys below this key should contain the path to
    #
    # - Simplicity Commander (`commander`), and
    # - the OTA update command line tool (`ota-dfu`, part of Simplicity Studio)
    #
    # for different operating systems. If the list for the current OS does not
    # do that, then the STH test will fail, unless the commands are already
    # accessible via the path environment variable (`$Env:Path` in Windows or
    # `$PATH` in Unix).
    Windows:
      # The paths below are the default install locations of `commander` in
      # Windows
      - C:\SiliconLabs\SimplicityStudio\v4\developer\adapter_packs\commander
      - C:\SiliconLabs\SimplicityStudio\v5\developer\adapter_packs\commander
      # This is the current default locations of `ota-dfu`, after you compiled
      # it. Please note, the version number inside the path. Depending on the
      # SDK we might need to extend this list in the future.
      - "C:\\SiliconLabs\\SimplicityStudio\\v4\\developer\\sdks\
         \\gecko_sdk_suite\\v2.7\\app\\bluetooth\\examples_ncp_host\
         \\ota_dfu\\exe"

GUI:
  HOST: localhost # Socket address of Matplotlib GUI
  PORT: 50007 # Port of Matplotlib GUI

Operator:
  # The name of the operator that executes the hardware tests
  Name: Dummy User

STH:
  Acceleration Sensor:
    Acceleration:
      # Maximum Acceleration of sensor in multiples of g₀ (= 9.807 m/s²)
      Maximum: 200
      # This value stores the maximum allowed ratio of noise to maximum
      # measurement value in dB. If the measured ratio is above this level, then
      # the tested STH will be considered faulty.
      Ratio Noise To Max Value: -55
      # Tolerance to expected (stationary) acceleration value (of 0 m/s²) in
      # multiples of g₀
      Tolerance: 3
    Self Test:
      Voltage:
        # Expected voltage difference between
        #
        # - the measured (stationary) acceleration voltage, and
        # - acceleration voltage when the self test is active
        #
        # in mV. For more information, please check the data sheet of the
        # accelerometer (ADXL1001).
        Difference: 160
        # Tolerance to the expected voltage difference in mV
        Tolerance: 30

  # An ever increasing (32 bit unsigned) number that describes the current
  # batch that this STH was a part of.
  Batch Number: 200

  Battery Voltage:
    Average: 3.6 # Expected value of power source voltage in Volt
    Tolerance: 0.6 # Tolerance for expected power source voltage in Volt
  Bluetooth:
    # Advertisement time 1 in ms
    Advertisement Time 1: 2000
    # Advertisement time 2 in ms
    Advertisement Time 2: 4000
    # Time to from disconnect or power on to sleep mode 1 in ms
    Sleep Time 1: 300000
    # Time to/from entering sleep mode 1 to sleep mode 2 in ms
    Sleep Time 2: 259200000

  Firmware:
    Location:
      # This value should contain the path to a complete image (bootloader and
      # application). This path will be interpreted in relation to the root of
      # the repository.
      Flash: ../STH/builds/manufacturingImageSthv2.1.10.hex
      OTA:   ../STH/builds/OtaServer.gbl
    # Code name of the current firmware release
    Release Name: Tanja

  # Global Trade Item Number
  GTIN: 0

  # The current version of the PCB design
  Hardware Revision: 1.3.5

  # This value specifies the current name of the STH unit
  Name: CGvXAd6B

  # OEM specific data
  OEM Data: [
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
     ]

  # The production date of the STH PCB in the format YYYY-MM-DD
  Production Date: 2019-07-03

  # Product name for the  manufacturer (maximum of 64 byte UTF-8 encoded text)
  Product Name: 0

  Programming Board:
    # Please store the serial number of the programming board that is connected
    # to the STH here. This number should be displayed in the right bottom
    # corner of the LC display, after you connect the programmer to a power
    # source
    Serial Number: 440120910
    COM Interface: COM3

  # Serial number for the manufacturer (maximum of 32 byte UTF-8 encoded text)
  Serial Number: 0

  Status:
    # Describe the status of the current STH hardware. This scalar should either
    # store the value `Bare BCP` or `Epoxied`.
    Bare BCP
