# Currently only the production tests of the STH use the following config file.

Commands:
  Path:
    # The keys below this key should contain the path to Simplicity Commander
    # (`commander`) for different operating systems. If the list for the current
    # OS does not do that, then the STH test will fail, unless `commander` is
    # already accessible via the path environment variable (`$Env:Path` in
    # Windows or `$PATH` in Unix).
    Windows:
      # This is the default install location of `commander` in Windows
      - C:\SiliconLabs\SimplicityStudio\v4\developer\adapter_packs\commander

STH:
  Acceleration Sensor:
    # Maximum Acceleration of sensor in multiples of g₀ (= 9.807 m/s²)
    Maximum Acceleration: 200
    # Tolerance to expected (stationary) acceleration value (of 0 m/s²) in
    # multiples of g₀
    Acceleration Tolerance: 3

  Battery Voltage:
    Average: 3.2 # Expected value of power source voltage in Volt
    Tolerance: 0.3 # Tolerance for expected power source voltage in Volt

  Name:
    # This value specifies the current name of the STH unit
    Blubb

  Programming Board:
    Serial Number:
      # Please store the serial number of the programming board that is
      # connected to the STH here. This number should be displayed in the
      # right bottom corner of the LC display, after you connect the programmer
      # to a power source
      440120910
  Firmware:
    # This value should contain the path to a complete image (bootloader and
    # application). Relative paths will be interpreted in relation to the
    # root of the repository.
    Location: ../STH/builds/v2.1.10/manufacturingImageSthv2.1.10.hex
